// <auto-generated />
using System;
using Confectionery.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Confectionery.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260317081334_AddIsOrderedToBaskasdad")]
    partial class AddIsOrderedToBaskasdad
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Basket", b =>
                {
                    b.Property<int>("Id_Basket")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Basket"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Id_Order")
                        .HasColumnType("int");

                    b.Property<int>("Id_User")
                        .HasColumnType("int");

                    b.Property<bool>("IsOrdered")
                        .HasColumnType("bit");

                    b.Property<decimal>("Total_Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id_Basket");

                    b.HasIndex("Id_Order");

                    b.HasIndex("Id_User");

                    b.ToTable("Baskets");
                });

            modelBuilder.Entity("Confectionery.Models.BasketCatalog", b =>
                {
                    b.Property<int>("Id_BasketCatalog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_BasketCatalog"));

                    b.Property<int>("Id_Basket")
                        .HasColumnType("int");

                    b.Property<int>("Id_Catalog")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id_BasketCatalog");

                    b.HasIndex("Id_Basket");

                    b.HasIndex("Id_Catalog");

                    b.ToTable("BasketCatalogs");
                });

            modelBuilder.Entity("Confectionery.Models.Catalog", b =>
                {
                    b.Property<int>("Id_Catalog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Catalog"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Id_Ctegory")
                        .HasColumnType("int");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PhotoContentType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PhotoFileName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long?>("PhotoSize")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id_Catalog");

                    b.HasIndex("Id_Ctegory");

                    b.ToTable("Catalog");
                });

            modelBuilder.Entity("Confectionery.Models.Category", b =>
                {
                    b.Property<int>("Id_Category")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Category"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id_Category");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Confectionery.Models.Order", b =>
                {
                    b.Property<int>("Id_Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Order"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_StatusOrder")
                        .HasColumnType("int");

                    b.Property<int>("Id_User")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id_Order");

                    b.HasIndex("Id_StatusOrder");

                    b.HasIndex("Id_User");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Confectionery.Models.Role", b =>
                {
                    b.Property<int>("Id_Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Role"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id_Role");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Confectionery.Models.StatusOrder", b =>
                {
                    b.Property<int>("Id_StatusOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_StatusOrder"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id_StatusOrder");

                    b.ToTable("StatusOrders");
                });

            modelBuilder.Entity("Confectionery.Models.User", b =>
                {
                    b.Property<int>("Id_User")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_User"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Id_Role")
                        .HasColumnType("int");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id_User");

                    b.HasIndex("Id_Role");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Basket", b =>
                {
                    b.HasOne("Confectionery.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("Id_Order");

                    b.HasOne("Confectionery.Models.User", "User")
                        .WithMany("Baskets")
                        .HasForeignKey("Id_User")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Confectionery.Models.BasketCatalog", b =>
                {
                    b.HasOne("Basket", "Basket")
                        .WithMany("BasketCatalogs")
                        .HasForeignKey("Id_Basket")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Confectionery.Models.Catalog", "Catalog")
                        .WithMany("BasketCatalogs")
                        .HasForeignKey("Id_Catalog")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Basket");

                    b.Navigation("Catalog");
                });

            modelBuilder.Entity("Confectionery.Models.Catalog", b =>
                {
                    b.HasOne("Confectionery.Models.Category", "Category")
                        .WithMany("Catalogs")
                        .HasForeignKey("Id_Ctegory")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Confectionery.Models.Order", b =>
                {
                    b.HasOne("Confectionery.Models.StatusOrder", "StatusOrder")
                        .WithMany("Orders")
                        .HasForeignKey("Id_StatusOrder")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Confectionery.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("Id_User")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StatusOrder");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Confectionery.Models.User", b =>
                {
                    b.HasOne("Confectionery.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("Id_Role")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Basket", b =>
                {
                    b.Navigation("BasketCatalogs");
                });

            modelBuilder.Entity("Confectionery.Models.Catalog", b =>
                {
                    b.Navigation("BasketCatalogs");
                });

            modelBuilder.Entity("Confectionery.Models.Category", b =>
                {
                    b.Navigation("Catalogs");
                });

            modelBuilder.Entity("Confectionery.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Confectionery.Models.StatusOrder", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Confectionery.Models.User", b =>
                {
                    b.Navigation("Baskets");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
